# Generated by Django 3.0 on 2019-12-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image_url',
            field=models.CharField(default=1, max_length=2083),
            preserve_default=False,
        ),
    ]
