# Generated by Django 3.0.1 on 2020-01-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_climate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalClimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Climate')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animal')),
            ],
        ),
    ]
