# Generated by Django 3.0.2 on 2020-01-13 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_animalclimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animals.Environment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animals.Type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnimalClimate',
        ),
    ]
