# Generated by Django 3.0.2 on 2020-01-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_auto_20200113_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
