# Generated by Django 3.0.2 on 2020-01-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_animal_climate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalClimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
