# Generated by Django 3.0.2 on 2020-01-13 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0012_animalclimate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalClimate',
        ),
    ]
