# Generated by Django 3.0.2 on 2020-01-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_auto_20200113_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='climate',
        ),
    ]
