# Generated by Django 3.0.2 on 2020-01-13 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0022_auto_20200113_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='climate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Climate'),
        ),
    ]
